### ISSUE TITLE
rssowlnix started crashing after 19.6.22

### ISSUE THREAD

**Issue by neiaberau** [Xyrio/RSSOwlnix#146]
rssowlnix started crashing since 20.6 when I click on one of the entries to be displayed, 
on 19.6 and before it still worked. might this be related to the removal of IE by Microsoft?

there are no errors in the log file, as far as I can see, 
from .log: 

!SESSION 2022-06-26 11:37:15.363 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_321
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.rssowl.ui 1 0 2022-06-26 11:37:30.511
!MESSAGE RSSOwlnix Starting Up (RSSOwlnix/2.9.0.202104110030 (Windows; U; en))
!SESSION 2022-06-26 11:43:41.837 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_321
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Command-line arguments:  -os win32 -ws win32 -arch x86_64

!ENTRY org.rssowl.ui 1 0 2022-06-26 11:43:44.505
!MESSAGE RSSOwlnix Starting Up (RSSOwlnix/2.9.0.202104110030 (Windows; U; en))

**Comment by neiaberau** [comment]
I can still find the iexplore executable, while it complains it will be replaced it is still there, 
so it seems it must be something else, is there a setting I can apply get more debug output?

**Comment by Xyrio** [comment]
what windows are you using? 10? 11?

try giving it more memory?
in `RSSOwlnix.ini` edit the line starting with -Xmx to something higher like -Xmx1024m

does it still crash with fresh database?
rename the folder `org.rssowl.core` so it creates a new database: `%userprofile%\.rssowlnix-beta\.metadata\.plugins\org.rssowl.core`

**Comment by neiaberau** [comment]
I thought that was in the log, but now I see it only says win ... 
- it is windows 10
- I already used -Xmx1024m,  so I tried it with -Xmx2048m, this did not help


with an empty database, I selected use recomende feeds, now it does not crash but complains 
An error has occurred. See error log for more details.
org.eclipse.ui.internal.ErrorEditorPart cannot be cast to org.rssowl.ui.internal.editors.feed.FeedView

whoever, after stop and restart, it no longer complains, and seems to work

so now I am confused. 



this was from the log from the first start, which did no longer occur after a restart
!ENTRY org.rssowl.ui 4 2 2022-06-27 08:09:51.074
!MESSAGE Problems occurred when invoking code from plug-in: "org.rssowl.ui".
!STACK 0
java.lang.ClassCastException: org.eclipse.ui.internal.ErrorEditorPart cannot be cast to org.rssowl.ui.internal.editors.feed.FeedView
	at org.rssowl.ui.internal.OwlUI.getFirstActiveFeedView(OwlUI.java:1510)
	at org.rssowl.ui.internal.OwlUI.internalOpenInFeedView(OwlUI.java:1805)
	at org.rssowl.ui.internal.OwlUI.openInFeedView(OwlUI.java:1740)
	at org.rssowl.ui.internal.OwlUI.openInFeedView(OwlUI.java:1726)
	at org.rssowl.ui.internal.OwlUI.openInFeedView(OwlUI.java:1714)
	at org.rssowl.ui.internal.OwlUI.openInFeedView(OwlUI.java:1703)
	at org.rssowl.ui.internal.views.explorer.BookMarkExplorer$2.open(BookMarkExplorer.java:353)
	at org.rssowl.ui.internal.views.explorer.BookMarkViewer$3.run(BookMarkViewer.java:224)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:47)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:176)
	at org.rssowl.ui.internal.views.explorer.BookMarkViewer.internalFireOpen(BookMarkViewer.java:221)
	at org.rssowl.ui.internal.views.explorer.BookMarkViewer.internalHandleOpen(BookMarkViewer.java:213)
	at org.rssowl.ui.internal.views.explorer.BookMarkViewer.access$1(BookMarkViewer.java:209)
	at org.rssowl.ui.internal.views.explorer.BookMarkViewer$2.handleOpen(BookMarkViewer.java:194)
	at org.rssowl.ui.internal.util.ViewerOpenStrategy.fireOpenEvent(ViewerOpenStrategy.java:147)
	at org.rssowl.ui.internal.util.ViewerOpenStrategy.mouseSelectItem(ViewerOpenStrategy.java:288)
	at org.rssowl.ui.internal.util.ViewerOpenStrategy.handleEvent(ViewerOpenStrategy.java:240)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4145)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3958)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3561)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:628)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.rssowl.ui.internal.Application.start(Application.java:122)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)

**Comment by Xyrio** [comment]
there are backups of the database you can try using them to not lose everything. 
rename the core folder back then switch the current rssowl.db with rssowl.db.onlinebak or one of the others (look at change date which ones are newer)

if all backups are corrupt you can still at least get your feed tree from the backup at `C:\Users\mux\.rssowlnix-beta\*.opml`. 
`File - Import... - Import Feeds from a file - choose an opml`

**Comment by neiaberau** [comment]
closing
