### ISSUE TITLE
Mvn build in RSSOwlnix root fails

### ISSUE THREAD

**Issue by DenverDaveH** [Xyrio/RSSOwlnix#160]
Hello, 
Here is the stack trace when I tried to build on my Win 10 Pro pc:
C:\Users\denve\RSSOwlnix> C:\Users\denve\Downloads\apache-maven-3.9.6-bin\apache-maven-3.9.6\bin\mvn clean verify -Dmaven.test.skip=true
---------------------------------------------------
constituent[0]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/conf/logging/
constituent[1]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/aopalliance-1.0.jar
constituent[2]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/commons-cli-1.5.0.jar
constituent[3]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/commons-codec-1.16.0.jar
constituent[4]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/commons-lang3-3.12.0.jar
constituent[5]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/failureaccess-1.0.1.jar
constituent[6]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/guava-32.0.1-jre.jar
constituent[7]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/guice-5.1.0.jar
constituent[8]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/httpclient-4.5.14.jar
constituent[9]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/httpcore-4.4.16.jar
constituent[10]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/jansi-2.4.0.jar
constituent[11]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/javax.annotation-api-1.3.2.jar
constituent[12]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/javax.inject-1.jar
constituent[13]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/jcl-over-slf4j-1.7.36.jar
constituent[14]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/maven-artifact-3.9.6.jar
constituent[15]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/maven-builder-support-3.9.6.jar
constituent[16]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/maven-compat-3.9.6.jar
constituent[17]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/maven-core-3.9.6.jar
constituent[18]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/maven-embedder-3.9.6.jar
constituent[19]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/maven-model-3.9.6.jar
constituent[20]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/maven-model-builder-3.9.6.jar
constituent[21]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/maven-plugin-api-3.9.6.jar
constituent[22]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/maven-repository-metadata-3.9.6.jar
constituent[23]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/maven-resolver-api-1.9.18.jar
constituent[24]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/maven-resolver-connector-basic-1.9.18.jar
constituent[25]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/maven-resolver-impl-1.9.18.jar
constituent[26]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/maven-resolver-named-locks-1.9.18.jar
constituent[27]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/maven-resolver-provider-3.9.6.jar
constituent[28]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/maven-resolver-spi-1.9.18.jar
constituent[29]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/maven-resolver-transport-file-1.9.18.jar
constituent[30]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/maven-resolver-transport-http-1.9.18.jar
constituent[31]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/maven-resolver-transport-wagon-1.9.18.jar
constituent[32]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/maven-resolver-util-1.9.18.jar
constituent[33]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/maven-settings-3.9.6.jar
constituent[34]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/maven-settings-builder-3.9.6.jar
constituent[35]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/maven-shared-utils-3.3.4.jar
constituent[36]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/maven-slf4j-provider-3.9.6.jar
constituent[37]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/org.eclipse.sisu.inject-0.9.0.M2.jar
constituent[38]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/org.eclipse.sisu.plexus-0.9.0.M2.jar
constituent[39]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/plexus-cipher-2.0.jar
constituent[40]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/plexus-component-annotations-2.1.0.jar
constituent[41]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/plexus-interpolation-1.26.jar
constituent[42]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/plexus-sec-dispatcher-2.0.jar
constituent[43]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/plexus-utils-3.5.1.jar
constituent[44]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/slf4j-api-1.7.36.jar
constituent[45]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/wagon-file-3.5.3.jar
constituent[46]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/wagon-http-3.5.3.jar
constituent[47]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/wagon-http-shared-3.5.3.jar
constituent[48]: file:/C:/Users/denve/Downloads/apache-maven-3.9.6-bin/apache-maven-3.9.6/lib/wagon-provider-api-3.5.3.jar
---------------------------------------------------
Exception in thread "main" java.lang.ExceptionInInitializerError
        at javax.crypto.Cipher.getInstance(Cipher.java:518)
        at sun.security.ssl.JsseJce.getCipher(JsseJce.java:189)
        at sun.security.ssl.SSLCipher.isTransformationAvailable(SSLCipher.java:483)
        at sun.security.ssl.SSLCipher.<init>(SSLCipher.java:472)
        at sun.security.ssl.SSLCipher.<clinit>(SSLCipher.java:81)
        at sun.security.ssl.CipherSuite.<clinit>(CipherSuite.java:69)
        at sun.security.ssl.SSLContextImpl.getApplicableSupportedCipherSuites(SSLContextImpl.java:345)
        at sun.security.ssl.SSLContextImpl.access$100(SSLContextImpl.java:46)
        at sun.security.ssl.SSLContextImpl$AbstractTLSContext.<clinit>(SSLContextImpl.java:577)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at java.security.Provider$Service.getImplClass(Provider.java:1728)
        at java.security.Provider$Service.newInstance(Provider.java:1686)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
        at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
        at javax.net.ssl.SSLContext.getDefault(SSLContext.java:96)
        at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:122)
        at org.eclipse.aether.transport.http.GlobalState.newConnectionManager(GlobalState.java:166)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at org.eclipse.aether.transport.http.GlobalState.getConnectionManager(GlobalState.java:145)
        at org.eclipse.aether.transport.http.LocalState.<init>(LocalState.java:62)
        at org.eclipse.aether.transport.http.HttpTransporter.<init>(HttpTransporter.java:197)
        at org.eclipse.aether.transport.http.HttpTransporterFactory.newInstance(HttpTransporterFactory.java:95)
        at org.eclipse.aether.internal.impl.DefaultTransporterProvider.newTransporter(DefaultTransporterProvider.java:94)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:128)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnectorFactory.newInstance(BasicRepositoryConnectorFactory.java:172)
        at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:122)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:536)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:449)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:261)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:243)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:234)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:175)
        at org.eclipse.aether.internal.impl.collect.DependencyCollectorDelegate.collectDependencies(DependencyCollectorDelegate.java:179)
        at org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:87)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:306)
        at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:212)
        at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveCoreExtension(DefaultPluginDependenciesResolver.java:155)
        at org.apache.maven.cli.internal.BootstrapCoreExtensionManager.resolveExtension(BootstrapCoreExtensionManager.java:174)
        at org.apache.maven.cli.internal.BootstrapCoreExtensionManager.resolveCoreExtensions(BootstrapCoreExtensionManager.java:115)
        at org.apache.maven.cli.internal.BootstrapCoreExtensionManager.loadCoreExtensions(BootstrapCoreExtensionManager.java:99)
        at org.apache.maven.cli.MavenCli.loadCoreExtensions(MavenCli.java:756)
        at org.apache.maven.cli.MavenCli.container(MavenCli.java:627)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:277)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
Caused by: java.lang.SecurityException: Can not initialize cryptographic mechanism
        at javax.crypto.JceSecurity.<clinit>(JceSecurity.java:93)
        ... 54 more
Caused by: java.lang.SecurityException: Cannot locate policy or framework files!
        at javax.crypto.JceSecurity.setupJurisdictionPolicies(JceSecurity.java:316)
        at javax.crypto.JceSecurity.access$000(JceSecurity.java:50)
        at javax.crypto.JceSecurity$1.run(JceSecurity.java:85)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.crypto.JceSecurity.<clinit>(JceSecurity.java:82)
        ... 54 more

C:\Users\denve\RSSOwlnix> C:\Users\denve\Downloads\apache-maven-3.9.6-bin\apache-maven-3.9.6\bin\mvn --version
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: C:\Users\denve\Downloads\apache-maven-3.9.6-bin\apache-maven-3.9.6
Java version: 1.8.0_333, vendor: Oracle Corporation, runtime: C:\Java\jdk1.8.0_333\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

C:\Users\denve\RSSOwlnix>java -version
java version "1.8.0_333"
Java(TM) SE Runtime Environment (build 1.8.0_333-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.333-b02, mixed mode)

I used git clone https://github.com/Xyrio/RSSOwlnix.git to get the latest version. 

It appears that my Java version is good right? 

I tried to use chocolatey but that errored out and I submitted a ticket there. Then I removed it and went this route. I do have Java 17 installed for a Udemy course. But I moved the Java 8 bin path up above all other Javas and set the Java Home to that version.

Looking forward to your reply.
Dave

**Comment by Xyrio** [comment]
try open jdk 11  https://adoptium.net/en-GB/temurin/releases/?version=11&package=jdk&os=windows&arch=x64

**Comment by DenverDaveH** [comment]
Closing as resolved with openjdk 11

**Comment by Xyrio** [comment]
you can export filtes to the opml file,
edit the opml file programatically,
import again

**Comment by DenverDaveH** [comment]
Is there any way to use an API to create filters so if I wanted to use Java or Python to just run a script and BAM it's done? 
Thanks

**Comment by Xyrio** [comment]
there is no API
