### ISSUE TITLE
RSSOwlnix crashes on startup

### ISSUE THREAD

**Issue by DaveOJ1** [Xyrio/RSSOwlnix#94]
Hi,

I was using an older version on Windows 10, but it started crashing on launch a few days ago. I updated to RSSOwlnix 2.8.0-beta and am still having issues.

The log file is attached.
[.log](https://github.com/Xyrio/RSSOwlnix/files/4826847/default.log)

**Comment by Xyrio** [comment]
try the following:
rename the `%userprofile%\.rssowlnix-beta` folder (or move its content)
start RSSOwlnix and see if it works
if yes stop RSSOwlnix then replace all files in the folder `%userprofile%\.rssowlnix-beta\.metadata\.plugins\org.rssowl.core` with files from same folder that you moved away. this will restore only your database but throw away all configuration/plugins stuff that can be redone like usual.

**Comment by Xyrio** [comment]
dev note:

!ENTRY org.eclipse.core.jobs 4 2 2020-06-21 22:20:30.093
!MESSAGE An internal error occurred during: "".
!STACK 0
java.lang.NullPointerException
	at org.rssowl.core.internal.persist.search.ModelSearchImpl.getCurrentSearcher(ModelSearchImpl.java:508)
	at org.rssowl.core.internal.persist.search.ModelSearchImpl.simpleSearch(ModelSearchImpl.java:350)
	at org.rssowl.core.internal.persist.search.ModelSearchImpl.searchNewsByLink(ModelSearchImpl.java:320)
	at org.rssowl.core.internal.persist.dao.NewsDAOImpl.doSearchNews(NewsDAOImpl.java:284)
	at org.rssowl.core.internal.persist.dao.NewsDAOImpl.searchNews(NewsDAOImpl.java:254)
	at org.rssowl.core.internal.persist.dao.NewsDAOImpl.getNewsFromLink(NewsDAOImpl.java:233)
	at org.rssowl.core.internal.persist.dao.NewsDAOImpl.setState(NewsDAOImpl.java:181)
	at org.rssowl.ui.internal.editors.feed.FeedView$25.run(FeedView.java:1446)
	at org.rssowl.ui.internal.util.JobRunner$4.run(JobRunner.java:164)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by DaveOJ1** [comment]
It worked! Thank you.

**Comment by Xyrio** [comment]
root problem seems to be `org.eclipse.swt.SWTError: No more handles`.
